TOTAL_SUN_TZU_QUOTES = 75

SUN_TZU_QUOTES = [
    "Appear weak when you are strong, and strong when you are weak",
    "Can you imagine what I would do if I could do all I can?",
    "If you know the enemy and know yourself you need not fear the results of a hundred battles.",
    "Keep your friends close, your enemies even closer.",
    "Know thy self, know thy enemy. A thousand battles, a thousand victories.",
    "The supreme art of war is to subdue the enemy without fighting.",
    "Let your plans be dark and as impenetrable as night, and when you move, fall like a thunderbolt.",
    "If you are far from the enemy, make him believe you are near.",
    "Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.",
    "In the midst of chaos, there is also opportunity.",
    "The general who wins the battle makes many calculations in his temple before the battle is fought. The general who loses makes but few calculations beforehand.",
    "Strategy without tactics is the slowest route to victory. Tactics without strategy is the noise before defeat.",
    "Victory comes from finding opportunities in problems.",
    "Do not engage an enemy more powerful than you. And if it is unavoidable and you do have to engage, then make sure you engage it on your terms, not on your enemy’s terms.",
    "If the mind is willing, the flesh could go on and on without many things.",
    "Even the finest sword plunged into salt water will eventually rust.",
    "Unhappy is the fate of one who tries to win his battles and succeed in his attacks without cultivating the spirit of enterprise, for the result is waste of time and general stagnation.",
    "A wise general makes a point of foraging of the enemy.",
    "The good fighters of old first put themselves beyond the possibility of defeat, and then waited for an opportunity of defeating the enemy.",
    "All war is deception.",
    "The greatest victory is that which requires no battle.",
    "There is no instance of a nation benefiting from prolonged warfare.",
    "Opportunities multiply as they are seized.",
    "The quality of decision is like the well-timed swoop of a falcon which enables it to strike and destroy its victim.",
    "It is more important to out-think your enemy, than to outfight him",
    "Move swift as the Wind and closely-formed as the Wood. Attack like the Fire and be still as the Mountain.",
    "He will win who knows when to fight and when not to fight.",
    "Do not press an enemy at bay.",
    "The skillful employer of men will employ the wise man, the brave man, the covetous man, and the stupid man.",
    "For them to perceive the advantage of defeating the enemy, they must also have their rewards.",
    "Treat your men as you would your own beloved sons. And they will follow you into the deepest valley.",
    "When the enemy is relaxed, make them toil. When full, starve them. When settled, make them move.",
    "Convince your enemy that he will gain very little by attacking you; this will diminish his enthusiasm.",
    "The peak efficiency of knowledge and strategy is to make conflict unnecessary.",
    "He will win who, prepared himself, waits to take the enemy unprepared.",
    "There is no instance of a country having benefited from prolonged warfare.",
    "You have to believe in yourself.",
    "When strong, avoid them. If of high morale, depress them. Seem humble to fill them with conceit. If at ease, exhaust them. If united, separate them. Attack their weaknesses. Emerge to their surprise.",
    "Build your opponent a golden bridge to retreat across.",
    "Energy may be likened to the bending of a crossbow; decision, to the releasing of the trigger.",
    "Sweat more during peace: bleed less during war.",
    "All men can see these tactics whereby I conquer, but what none can see is the strategy out of which victory is evolved.",
    "Concentrate your energy and hoard your strength.",
    "The opportunity of defeating the enemy is provided by the enemy himself.",
    "When envoys are sent with compliments in their mouths, it is a sign that the enemy wishes for a truce.",
    "Who wishes to fight must first count the cost",
    "If ignorant both of your enemy and yourself, you are certain to be in peril.",
    "One may know how to conquer without being able to do it.",
    "The art of giving orders is not to try to rectify the minor blunders and not to be swayed by petty doubts.",
    "The line between disorder and order lies in logistics.",
    "If your opponent is of choleric temper, seek to irritate him. Pretend to be weak, that he may grow arrogant.",
    "Leadership is a matter of intelligence, trustworthiness, humaneness, courage, and sternness.",
    "If the enemy know not where he will be attacked, he must prepare in every quarter, and so be everywhere weak.",
    "Be extremely subtle, even to the point of formlessness. Be extremely mysterious, even to the point of soundlessness. Thereby you can be the director of the opponent’s fate.",
    "Those who win every battle are not really skillful—those who render others’ armies helpless without fighting are the best of all.",
    "If he is secure at all points, be prepared for him. If he is in superior strength, evade him.",
    "Every animal with blood in its veins and horns on its head will fight when it is attacked.",
    "Know the enemy, know yourself and victory is never in doubt, not in a hundred battles.",
    "Those skilled in warfare move the enemy, and are not moved by the enemy.",
    "Knowing the enemy enables you to take the offensive, knowing yourself enables you to stand on the defensive.",
    "Using order to deal with the disorderly, using calm to deal with the clamorous, is mastering the heart.",
    "Move not unless you see an advantage; use not your troops unless there is something to be gained; fight not unless the position is critical.",
    "The victorious army is victorious first and seeks battle later; the defeated army seeks battle first and seeks victory later.",
    "If words of command are not clear and distinct, if orders are not thoroughly understood, the general is to blame. But if his orders are clear, and the soldiers nevertheless disobey, then it is the fault of their officers.",
    "He wins his battles by making no mistakes.",
    "It is easy to love your friend, but sometimes the hardest lesson to learn is to love your enemy.",
    "All wars are won or lost before they are ever fought.",
    "Rewards for good service should not be deferred a single day.",
    "If you are strong, appear weak. But if you are weak, appear strong.",
    "Ponder and deliberate before you make a move.",
    "When your opponent gives you an opening, be swift as a hare.",
    "The whole secret lies in confusing the enemy, so that he cannot fathom our real intent.",
    "The height of strategy is to attack your opponent’s strategy.",
    "What the ancients called a clever fighter is one who not only wins but excels in winning with ease.",
    "Correct your mistake as soon as you have found it.",
]
