SUN_TZU_QUOTES = [
    "Appear weak when you are strong, and strong when you are weak",
    "Can you imagine what I would do if I could do all I can?",
    "If you know the enemy and know yourself you need not fear the results of a hundred battles.",
    "Keep your friends close, your enemies even closer.",
    "Know thy self, know thy enemy. A thousand battles, a thousand victories.",
    "The supreme art of war is to subdue the enemy without fighting.",
    "Let your plans be dark and as impenetrable as night, and when you move, fall like a thunderbolt.",
    "If you are far from the enemy, make him believe you are near.",
    "Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.",
    "In the midst of chaos, there is also opportunity.",
    "The general who wins the battle makes many calculations in his temple before the battle is fought. The general who loses makes but few calculations beforehand.",
    "Strategy without tactics is the slowest route to victory. Tactics without strategy is the noise before defeat.",
    "Victory comes from finding opportunities in problems.",
    "Do not engage an enemy more powerful than you. And if it is unavoidable and you do have to engage, then make sure you engage it on your terms, not on your enemy’s terms.",
    "If the mind is willing, the flesh could go on and on without many things.",
    "Even the finest sword plunged into salt water will eventually rust.",
    "Unhappy is the fate of one who tries to win his battles and succeed in his attacks without cultivating the spirit of enterprise, for the result is waste of time and general stagnation.",
    "A wise general makes a point of foraging of the enemy.",
    "The good fighters of old first put themselves beyond the possibility of defeat, and then waited for an opportunity of defeating the enemy.",
    "All war is deception.",
    "The greatest victory is that which requires no battle.",
    "There is no instance of a nation benefiting from prolonged warfare.",
    "Opportunities multiply as they are seized.",
    "The quality of decision is like the well-timed swoop of a falcon which enables it to strike and destroy its victim.",
    "It is more important to out-think your enemy, than to outfight him",
    "Move swift as the Wind and closely-formed as the Wood. Attack like the Fire and be still as the Mountain.",
    "He will win who knows when to fight and when not to fight.",
    "Do not press an enemy at bay.",
    "The skillful employer of men will employ the wise man, the brave man, the covetous man, and the stupid man.",
    "For them to perceive the advantage of defeating the enemy, they must also have their rewards.",
    "Treat your men as you would your own beloved sons. And they will follow you into the deepest valley.",
    "When the enemy is relaxed, make them toil. When full, starve them. When settled, make them move.",
    "Convince your enemy that he will gain very little by attacking you; this will diminish his enthusiasm.",
    "The peak efficiency of knowledge and strategy is to make conflict unnecessary.",
    "He will win who, prepared himself, waits to take the enemy unprepared.",
    "There is no instance of a country having benefited from prolonged warfare.",
    "You have to believe in yourself.",
    "When strong, avoid them. If of high morale, depress them. Seem humble to fill them with conceit. If at ease, exhaust them. If united, separate them. Attack their weaknesses. Emerge to their surprise.",
    "Build your opponent a golden bridge to retreat across.",
    "Energy may be likened to the bending of a crossbow; decision, to the releasing of the trigger.",
    "Sweat more during peace: bleed less during war.",
    "All men can see these tactics whereby I conquer, but what none can see is the strategy out of which victory is evolved.",
    "Concentrate your energy and hoard your strength.",
    "The opportunity of defeating the enemy is provided by the enemy himself.",
    "When envoys are sent with compliments in their mouths, it is a sign that the enemy wishes for a truce.",
    "Who wishes to fight must first count the cost",
    "If ignorant both of your enemy and yourself, you are certain to be in peril.",
    "One may know how to conquer without being able to do it.",
    "The art of giving orders is not to try to rectify the minor blunders and not to be swayed by petty doubts.",
    "The line between disorder and order lies in logistics.",
    "If your opponent is of choleric temper, seek to irritate him. Pretend to be weak, that he may grow arrogant.",
    "Leadership is a matter of intelligence, trustworthiness, humaneness, courage, and sternness.",
    "If the enemy know not where he will be attacked, he must prepare in every quarter, and so be everywhere weak.",
    "Be extremely subtle, even to the point of formlessness. Be extremely mysterious, even to the point of soundlessness. Thereby you can be the director of the opponent’s fate.",
    "Those who win every battle are not really skillful—those who render others’ armies helpless without fighting are the best of all.",
    "If he is secure at all points, be prepared for him. If he is in superior strength, evade him.",
    "Every animal with blood in its veins and horns on its head will fight when it is attacked.",
    "Know the enemy, know yourself and victory is never in doubt, not in a hundred battles.",
    "Those skilled in warfare move the enemy, and are not moved by the enemy.",
    "Knowing the enemy enables you to take the offensive, knowing yourself enables you to stand on the defensive.",
    "Using order to deal with the disorderly, using calm to deal with the clamorous, is mastering the heart.",
    "Move not unless you see an advantage; use not your troops unless there is something to be gained; fight not unless the position is critical.",
    "The victorious army is victorious first and seeks battle later; the defeated army seeks battle first and seeks victory later.",
    "If words of command are not clear and distinct, if orders are not thoroughly understood, the general is to blame. But if his orders are clear, and the soldiers nevertheless disobey, then it is the fault of their officers.",
    "He wins his battles by making no mistakes.",
    "It is easy to love your friend, but sometimes the hardest lesson to learn is to love your enemy.",
    "All wars are won or lost before they are ever fought.",
    "Rewards for good service should not be deferred a single day.",
    "If you are strong, appear weak. But if you are weak, appear strong.",
    "Ponder and deliberate before you make a move.",
    "When your opponent gives you an opening, be swift as a hare.",
    "The whole secret lies in confusing the enemy, so that he cannot fathom our real intent.",
    "The height of strategy is to attack your opponent’s strategy.",
    "What the ancients called a clever fighter is one who not only wins but excels in winning with ease.",
    "Correct your mistake as soon as you have found it.",
]


ALBERT_EINSTEIN = [
    "Genius is 1% talent and 99% hard work",
    "I must be willing to give up what I am in order to become what I will be",
    "I’d rather be an optimist and a fool than a pessimist and right",
    "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking",
    "In the middle of difficulty lies opportunity",
    "There are two ways to live: you can live as if nothing is a miracle; you can live as if everything is a miracle",
    "I speak to everyone in the same way, whether he is the garbage man or the president of the university",
    "Only a life lived for others is a life worthwhile",
    "A table, a chair, a bowl of fruit and a violin; what else does a man need to be happy?",
    "Nothing happens until something moves",
    "Only those who attempt the absurd can achieve the impossible",
    "If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales",
    "If A is a success in life, then A equals x plus y plus z. Work is x; y is play; and z is keeping your mouth shut",
    "I am enough of an artist to draw freely upon my imagination. Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world",
    "A clever person solves a problem. A wise person avoids it",
    "Life is like riding a bicycle. To keep your balance, you must keep moving",
    "The important thing is to not stop questioning. Curiosity has its own reason for existing",
    "A true genius admits that he/she knows nothing",
    "If you can’t explain it to a six year old, you don’t understand it yourself",
    "Everybody is a genius. But if you judge a fish by its ability to climb a tree, it will live its whole life believing that it is stupid",
    "I think and think for months and years. Ninety-nine times, the conclusion is false. The hundredth time I am right",
    "What is right is not always popular and what is popular is not always right",
    "We dance for laughter, we dance for tears, we dance for madness, we dance for fears, we dance for hopes, we dance for screams, we are the dancers, we create the dreams",
    "Any fool can know. The point is to understand",
    "The best way to cheer yourself is to cheer somebody else up", "Imagination is more important than knowledge",
    "Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning",
    "Only two things are infinite, the universe and human stupidity, and I’m not sure about the former",
    "Most people say that it is the intellect which makes a great scientist. They are wrong: it is character",
    "If you want to live a happy life, tie it to a goal, not to people or things",
    "Everything should be made as simple as possible, but not simpler",
    "Look deep into nature, and then you will understand everything better",
    "When the solution is simple, God is answering",
    "Weakness of attitude becomes weakness of character",
    "Insanity: doing the same thing over and over again and expecting different results",
    "Imagination is everything. It is the preview of life’s coming attractions",
    "Education is what remains after one has forgotten what one has learned in school",
    "Human beings must have action; and they will make it if they cannot find i",
    "Great spirits have always encountered violent opposition from mediocre mids",
    "Coincidence is God’s way of remaining anonymous",
    "A person who never made a mistake never tried anything new",
    "The difference between stupidity and genius is that genius has its limits",
    "The only source of knowledge is experience",
    "Logic will get you from A to B. Imagination will take you everywhere",
    "Force always attracts men of low morality",
    "The woman who follows the crowd will usually go no further than the crowd. The woman who walks alone is likely to find herself in places no one has ever been before",
    "Anger dwells only in the bosom of fools",
    "A ship is always safe at the shore – but that is NOT what it is built for",
    "We still do not know one thousandth of one percent of what nature has revealed to us",
    "The only real valuable thing is intuition",
    "The world is a dangerous place to live; not because of the people who are evil, but because of the people who don’t do anything about it",
    "The value of a man should be seen in what he gives and not in what he is able to receive",
    "Try not to become a man of success, but rather try to become a man of value",
    "Once we accept our limits, we go beyond them",
    "Whoever is careless with the truth in small matters cannot be trusted with important matters",
    "I believe in intuitions and inspirations…I sometimes FEEL that I am right. I do not KNOW that I am",
    "The only way to escape the corruptible effect of praise is to go on working",
    "The true sign of intelligence is not knowledge but imagination",
    "Intellectuals solve problems, geniuses prevent them",
    "To raise new questions, new possibilities, to regard old problems from a new angle, requires creative imagination and marks real advance in science",
    "God always takes the simplest way",
    "Small is the number of people who see with their eyes and think with their minds",
    "Anyone who doesn’t take truth seriously in small matters cannot be trusted in large ones either",
    "Joy in looking and comprehending is nature’s most beautiful gift",
    "I have no special talent. I am only passionately curious.",
    "Peace cannot be kept by force; it can only be achieved by understanding",
    "It is the supreme art of the teacher to awaken joy in creative expression and knowledge",
    "Before God we are all equally wise – and equally foolish",
    "It’s not that I’m so smart, it’s just that I stay with problems longer",
    "I cannot imagine a God who rewards and punishes the objects of his creation and is but a reflection of human frailty",
    "The important thing is not to stop questioning. Curiosity has its own reason for existing",
    "A question that sometimes drives me hazy: am I or are the others crazy?",
    "The monotony and solitude of a quiet life stimulates the creative mind",
    "Few are those who see with their own eyes and feel with their own hearts",
    "If the facts don’t fit the theory, change the facts",
    "Science without religion is lame, religion without science is blind",
    "Unthinking respect for authority is the greatest enemy of truth",
    "If you can’t explain it simply, you don’t understand it well enough",
    "The faster you go, the shorter you are",
    "The only reason for time is so that everything doesn’t happen at once",
    "My religion consists of a humble admiration of the illimitable superior spirit who reveals himself in the slight details we are able to perceive with our frail and feeble mind",
    "I live in that solitude which is painful in youth, but delicious in the years of maturity",
    "The gift of fantasy has meant more to me than my talent for absorbing positive knowledge",
    "All religions, arts and sciences are branches of the same tree",
    "The most beautiful thing we can experience is the mysterious. It is the source of all true art and science",
    "The hardest thing to understand in the world is the income tax",
    "Information is not knowledge",
    "Reading, after a certain age, diverts the mind too much from its creative pursuits. Any man who reads too much and uses his own brain too little falls into lazy habits of thinking",
    "Memory is deceptive because it is colored by today’s events",
    "If you are out to describe the truth, leave elegance to the tailor",
    "Everyone should be respected as an individual, but no one idolized",
    "Any man who can drive safely while kissing a pretty girl is simply not giving the kiss the attention it deserves",
    "In order to be an immaculate member of a flock of sheep, one must above all be a sheep oneself",
    "Any intelligent fool can make things bigger and more complex… It takes a touch of genius – and a lot of courage to move in the opposite direction",
    "The distinction between the past, present and future is only a stubbornly persistent illusion",
    "Once you can accept the universe as matter expanding into nothing that is something, wearing stripes with plaid comes easy",
    "We shall require a substantially new manner of thinking if mankind is to survive",
    "The fear of death is the most unjustified of all fears, for there’s no risk of accident for someone who’s dead",
    "It is only to the individual that a soul is given",
    "We cannot solve our problems with the same thinking we used when we created them",
]


LITTLE_PRINCE = [
    "And now here is my secret, a very simple secret: It is only with the heart that one can see rightly; what is essential is invisible to the eye.",
    "All grown-ups were once children... but only few of them remember it.",
    "It is the time you have wasted for your rose that makes your rose so important.",
    "The most beautiful things in the world cannot be seen or touched, they are felt with the heart.",
    "I must endure the presence of a few caterpillars if I wish to become acquainted with the butterflies.",
    "A rock pile ceases to be a rock pile the moment a single man contemplates it, bearing within him the image of a cathedral.",
    "But if you tame me, then we shall need each other. To me, you will be unique in all the world. To you, I shall be unique in all the world.",
    "But the conceited man did not hear him. Conceited people never hear anything but praise.",
    "Words are the source of misunderstandings.",
    "It is much more difficult to judge oneself than to judge others. If you succeed in judging yourself rightly, then you are indeed a man of true wisdom.",
    "What matters most are the simple pleasures so abundant that we can all enjoy them...Happiness doesn't lie in the objects we gather around us. To find it, all we need to do is open our eyes.",
    "It's the time you spent on your rose that makes your rose so important...People have forgotten this truth, but you mustn't forget it. You become responsible forever for what you've tamed. You're responsible for your rose.",
    "He fell as gently as a tree falls. There was not even any sound.",
]


JOHN_GREEN = [
    "As he read, I fell in love the way you fall asleep: slowly, and then all at once.",
    "You don't get to choose if you get hurt in this world... But you do have some say in who hurts you. I like my choices.",
    "Some infinities are bigger than other infinities.",
    "The only way out of the labyrinth of suffering is to forgive.",
    "The marks humans leave are too often scars.",
    "Thomas Edison's last words were \"It's very beautiful over there\". I don't know where there is, but I believe it's somewhere, and I hope it's beautiful.",
    "The world is not a wish-granting factory.",
    "You can love someone so much... But you can never love people as much as you can miss them.",
    "What is the point of being alive if you don't at least try to do something remarkable?",
    "What a treacherous thing to believe that a person is more than a person.",
    "Maybe our favorite quotations say more about us than about the stories and people we're quoting.",
    "Imagining the future is a kind of nostalgia. (...) You spend your whole life stuck in the labyrinth, thinking about how you'll escape it one day, and how awesome it will be, and imagining that future keeps you going, but you never do it. You just use the future to escape the present.",
    "That's always seemed so ridiculous to me, that people want to be around someone because they're pretty. It's like picking your breakfeast cereals based on color instead of taste.",
    "It is so hard to leave—until you leave. And then it is the easiest goddamned thing in the world.",
    "Some tourists think Amsterdam is a city of sin, but in truth it is a city of freedom. And in freedom, most people find sin.",
    "I may die young, but at least I'll die smart.",
    "Some people have lives; some people have music.",
    "It always shocked me when I realized that I wasn’t the only person in the world who thought and felt such strange and awful things.",
    "What you must understand about me is that I’m a deeply unhappy person.",
    "If you don't imagine, nothing ever happens at all.",
    "Francois Rabelais. He was a poet. And his last words were \"I go to seek a Great Perhaps.\" That's why I'm going. So I don't have to wait until I die to start seeking a Great Perhaps.",
    "I'm a grenade and at some point I'm going to blow up and I would like to minimize the casualties, okay?",
    "You don't remember what happened. What you remember becomes what happened.",
    "You gave me a forever within the numbered days, and I'm grateful.",
    "I didn’t need you, you idiot. I picked you. And then you picked me back.",
    "But it is the nature of stars to cross, and never was Shakespeare more wrong than when he has Cassius note:\n*  The fault, dear Brutus, is not in our stars*\n*  But in ourselves.*",
    "You like someone who can't like you back because unrequited love can be survived in a way that once-requited love cannot.",
    "Sometimes you lose a battle. But mischief always wins the war.",
    "It is easy to forget how full the world is of people, full to bursting, and each of them imaginable and consistently misimagined.",
    "I just did some calculations and I've been able to determine that you're full of shit.",
    "There is no shortage of fault to be found amid our stars.",
    "We need never be hopeless because we can never be irreperably broken.",
    "I try to live life so that I can live with myself.",
    "As much as life can suck, it always beats the alternative.",
    "There's some people in this world who you can just love and love and love no matter what.",
    "I'm starting to realize that people lack good mirrors. It's so hard for anyone to show us how we look, & so hard for us to show anyone how we feel.",
    "If people could see me the way I see myself - if they could live in my memories - would anyone love me?",
    "The weird thing about houses is that they almost always look like nothing is happening inside of them, even though they contain most of our lives. I wondered if that was sort of the point of architecture.",
    "If only we could see the endless string of consequences that result from our smallest actions. But we can't know better until knowing better is useless.",
    "Peeing is like a good book in that it is very, very hard to stop once you start.",
    "Your now is not your forever.",
    "What matters to you defines your mattering.",
    "At some point, you gotta stop looking up at the sky, or one of these days you'll look back down and see that you floated away, too.",
    "Not that smart. Not that hot. Not that nice. Not that funny. That's me: I'm not that.",
    "Isn't it also that on some fundamental level we find it difficult to understand that other people are human beings in the same way that we are? We idealize them as gods or dismiss them as animals.",
    "If people were like rain, I was like drizzle and she was a hurricane.",
    "Our fearlessness shall be our secret weapon.",
    "You do not immortalize the lost by writing about them. Language buries, but does not resurrect.",
    "\"Sometimes people don't understand the promises they're making when they make them.\"\n\"Right, of course. But you keep the promise anyway. That’s what love is. Love is keeping the promise anyway.\"",
    "That's the thing about pain. It demands to be felt",
]


QUOTES_DICTIONARY = {
    "suntzu": {
        "name": "Sun Tzu",
        "quotes": SUN_TZU_QUOTES,
    },
    "alberteinstein": {
        "name": "Albert Einstein",
        "quotes": ALBERT_EINSTEIN,
    },
    "saintexupery": {
        "name": "Antoine de Saint-Exupéry",
        "quotes": LITTLE_PRINCE,
    },
    "johngreen": {
        "name": "Albert Einstein",
        "quotes": JOHN_GREEN,
    },
}
